Repository spdx/license-list-XML, pull requests merged in 2020-11, with the labels that each got.

#1128 Add CC-BY-3.0-US license and test
  src/CC-BY-3.0-US.xml
  test/simpleTestForGenerator/CC-BY-3.0-US.txt
Labels: new license/exception request, new license/exception: Accepted

#1135 update links
  CONTRIBUTING.md
Labels: documentation

#1074 Adding the Business Source License 1.1 (BUSL-1.1)
  src/BUSL-1.1.xml
  test/simpleTestForGenerator/BUSL-1.1.txt
Labels: new license/exception request

#1152 Add release notes for 3.11
  RELEASE-NOTES.md
Labels: documentation
