Repository spdx/license-list-XML, pull requests merged in 2021-07, with the labels that each got.

#1286 BSD-3-Clause-No-Military-License: remove extra p tags
  src/BSD-3-Clause-No-Military-License.xml
Labels: minor updates to file

#1278 Adding replaceable text to GCC 2.0 exception
  src/exceptions/GCC-exception-2.0.xml
Labels: XML markup change

#1262 Add NLOD-2.0
  src/NLOD-2.0.xml
  test/simpleTestForGenerator/NLOD-2.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1279 Add a version number to NLOD-1.0
  src/NLOD-1.0.xml
  test/simpleTestForGenerator/NLOD-1.0.txt
Labels: minor updates to file

#1271 Update crossRef for Apache-2.0 to use https
  src/Apache-2.0.xml
Labels: minor updates to file

#1272 Update MPL-2.0 crossRef to use https
  src/MPL-2.0.xml
Labels: minor updates to file

#1299 Remove duplicated "the" from BSD-4-Clause.txt file
  test/simpleTestForGenerator/BSD-4-Clause.txt
Labels: minor updates to file

#1294 Assorted improvements to documentation
  DOCS/new-license-workflow.md
Labels: documentation

#1303 Add new URL for the ISC license
  src/ISC.xml
Labels: minor updates to file
