Repository spdx/license-list-XML, pull requests merged in 2021-11, with the labels that each got.

#1354 Use generic copyright in Linux-man-pages-copyleft
  test/simpleTestForGenerator/Linux-man-pages-copyleft.txt
Labels: minor updates to file

#1350 Make BSD-1-Clause copyright consistent with others
  src/BSD-1-Clause.xml
  test/simpleTestForGenerator/BSD-1-Clause.txt
Labels: minor updates to file

#1351 Add Community-Spec-1.0
  src/Community-Spec-1.0.xml
  test/simpleTestForGenerator/Community-Spec-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1347 Unicode-DFS-2016 - add optional tags
  src/Unicode-DFS-2016.xml
Labels: XML markup change

#1357 Add FDK-AAC
  src/FDK-AAC.xml
  test/simpleTestForGenerator/FDK-AAC.txt
Labels: new license/exception request, new license/exception: Accepted

#1341 Add COIL 1.0 license info
  src/COIL-1.0.xml
  test/simpleTestForGenerator/COIL-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1358 COIL: add licenselistversion tag
  src/COIL-1.0.xml
Labels: minor updates to file

#1359 Add release notes for 3.15
  RELEASE-NOTES.md
Labels: documentation

#1363 BSD-3-Clause - remove "all rights reserved"
  src/BSD-2-Clause.xml
  src/BSD-3-Clause.xml
  test/simpleTestForGenerator/BSD-2-Clause.txt
  test/simpleTestForGenerator/BSD-3-Clause.txt
Labels: minor updates to file
