Repository spdx/license-list-XML, pull requests merged in 2021-05, with the labels that each got.

#1237 ISC: Make copyright notice descriptive
  src/ISC.xml
Labels: XML markup change

#1256 Add new URL for the FreeType Project License (FTL)
  src/FTL.xml
Labels: minor updates to file

#1248 CONTRIBUTING: fix some formatting
  CONTRIBUTING.md
Labels: documentation

#1226 Fix NCGL-UK-2.0 metadata typos
  src/NCGL-UK-2.0.xml
Labels: minor updates to file

#1254 Assorted improvements to README.md
  README.md
Labels: documentation

#909 Remove the optional https
  src/AGPL-3.0-only.xml
  src/AGPL-3.0-or-later.xml
  src/AGPL-3.0.xml
  src/CC-BY-ND-2.0.xml
  src/GPL-3.0+.xml
  src/GPL-3.0-only.xml
  src/GPL-3.0-or-later.xml
  src/GPL-3.0.xml
  src/LGPL-3.0+.xml
  src/LGPL-3.0-only.xml
  src/LGPL-3.0-or-later.xml
  src/LGPL-3.0.xml
Labels: documentation, technical issue

#1252 Update CAL-1.0-Combined-Work-Exception.xml
  src/CAL-1.0-Combined-Work-Exception.xml
  test/simpleTestForGenerator/CAL-1.0-Combined-Work-Exception.txt
Labels: minor updates to file

#1251 Update CAL-1.0.xml
  src/CAL-1.0.xml
  test/simpleTestForGenerator/CAL-1.0.txt
Labels: minor updates to file

#1257 Remove dash from CC license name for consistency
  src/CC-BY-SA-3.0-AT.xml
Labels: minor updates to file

#1250 add reference to LicenseRef-
  DOCS/request-new-license.md
Labels: documentation

#1249 remove reference to older "overview" webpage
  DOCS/README.md
Labels: documentation

#1260 Add Common Documentation License (CDL-1.0)
  src/CDL-1.0.xml
  test/simpleTestForGenerator/CDL-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1259 New license: BSD-3-Clause-No-Military-License
  src/BSD-3-Clause-No-Military-License.xml
  test/simpleTestForGenerator/BSD-3-Clause-No-Military-License.txt
Labels: new license/exception request, new license/exception: Accepted

#1263 0BSD - make copyright notice generic
  src/0BSD.xml
  test/simpleTestForGenerator/0BSD.txt
Labels: minor updates to file
