Repository spdx/license-list-XML, pull requests merged in 2021-02, with the labels that each got.

#1156 Fix typo in BUSL-1.1
  src/BUSL-1.1.xml
Labels: minor updates to file

#1162 Add crossRef to EUPL-1.2.xml
  src/EUPL-1.2.xml
Labels: minor updates to file

#1153 Add missing item for 3.11 release notes
  RELEASE-NOTES.md
Labels: documentation

#1167 Show the new (and source) URL
  src/Artistic-2.0.xml
Labels: XML markup change

#1175 Add license files for FreeBSD-DOC #1111
  src/FreeBSD-DOC.xml
  test/simpleTestForGenerator/FreeBSD-DOC.txt
Labels: new license/exception request, new license/exception: Accepted

#1179 updates to MPL-2.0-nocopyleft-exception-
  src/MPL-2.0-no-copyleft-exception.xml
Labels: minor updates to file

#1181 update full names for ODC licenses
  src/ODbL-1.0.xml
  src/PDDL-1.0.xml
  test/simpleTestForGenerator/ODbL-1.0.txt
  test/simpleTestForGenerator/PDDL-1.0.txt
Labels: minor updates to file

#1184 Add BSD-4-Clause-Shortened #1087
  src/BSD-4-Clause-Shortened.xml
  test/simpleTestForGenerator/BSD-4-Clause-Shortened.txt
Labels: new license/exception request, new license/exception: Accepted

#1180 add Notes for deprecated licenses
  src/GPL-2.0-with-GCC-exception.xml
  src/GPL-2.0-with-autoconf-exception.xml
  src/GPL-2.0-with-bison-exception.xml
  src/GPL-2.0-with-classpath-exception.xml
  src/GPL-2.0-with-font-exception.xml
  src/GPL-3.0-with-GCC-exception.xml
  src/GPL-3.0-with-autoconf-exception.xml
  src/StandardML-NJ.xml
  src/eCos-2.0.xml
  src/wxWindows.xml
Labels: minor updates to file

#1183 Add DRL-1.0
  src/DRL-1.0.xml
  test/simpleTestForGenerator/DRL-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1182 update Contributing to add note about complete submission
  CONTRIBUTING.md
Labels: documentation

#1189 Add additional crossRef for O-UDA-1.0
  src/O-UDA-1.0.xml
Labels: minor updates to file

#1187 Add OGDL-Taiwan-1.0
  src/OGDL-Taiwan-1.0.xml
  test/simpleTestForGenerator/OGDL-Taiwan-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1198 Update CERN-OHL-P-2.0.xml
  src/CERN-OHL-P-2.0.xml
Labels: minor updates to file

#1197 Update CERN-OHL-S-2.0.xml
  src/CERN-OHL-S-2.0.xml
Labels: minor updates to file

#1196 Update CERN-OHL-W-2.0.xml
  src/CERN-OHL-W-2.0.xml
Labels: minor updates to file
