Repository spdx/license-list-XML, pull requests merged in 2021-03, with the labels that each got.

#1188 Add NAIST-2003
  src/NAIST-2003.xml
  test/simpleTestForGenerator/NAIST-2003.txt
Labels: new license/exception request, new license/exception: Accepted

#1201 New License: BSD-3-Clause-Modification
  src/BSD-3-Clause-Modification.xml
  test/simpleTestForGenerator/BSD-3-Clause-Modification.txt
Labels: new license/exception request, new license/exception: Accepted

#1213 Add C-UDA-1.0
  src/C-UDA-1.0.xml
  test/simpleTestForGenerator/C-UDA-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1214 Add GD license
  src/GD.xml
  test/simpleTestForGenerator/GD.txt
Labels: new license/exception request, new license/exception: Accepted

#1215 ImageMagick: add note regarding Apache-2.0
  src/ImageMagick.xml
Labels: minor updates to file

#1217 Add CC-BY-SA-2.1-JP
  src/CC-BY-SA-2.1-JP.xml
  test/simpleTestForGenerator/CC-BY-SA-2.1-JP.txt
Labels: new license/exception request, new license/exception: Accepted

#1218 Add MIT-Modern-Variant
  src/MIT-Modern-Variant.xml
  test/simpleTestForGenerator/MIT-Modern-Variant.txt
Labels: new license/exception request, new license/exception: Accepted

#1219 Add release notes for 3.12
  RELEASE-NOTES.md
Labels: documentation
