Repository spdx/license-list-XML, pull requests merged in 2021-08, with the labels that each got.

#1283 Add CC-...-3.0-DE licenses
  src/CC-BY-3.0-DE.xml
  src/CC-BY-NC-3.0-DE.xml
  src/CC-BY-NC-ND-3.0-DE.xml
  src/CC-BY-NC-SA-3.0-DE.xml
  src/CC-BY-ND-3.0-DE.xml
  src/CC-BY-SA-3.0-DE.xml
  test/simpleTestForGenerator/CC-BY-3.0-DE.txt
  test/simpleTestForGenerator/CC-BY-NC-3.0-DE.txt
  test/simpleTestForGenerator/CC-BY-NC-ND-3.0-DE.txt
  test/simpleTestForGenerator/CC-BY-NC-SA-3.0-DE.txt
  test/simpleTestForGenerator/CC-BY-ND-3.0-DE.txt
  test/simpleTestForGenerator/CC-BY-SA-3.0-DE.txt
Labels: new license/exception request, new license/exception: Accepted

#1305 Add markup to zlib-acknowledgement.xml
  src/zlib-acknowledgement.xml
Labels: XML markup change

#1307 Add CC-BY-NC-SA-2.0-FR and CC-BY-3.0-NL
  src/CC-BY-3.0-NL.xml
  src/CC-BY-NC-SA-2.0-FR.xml
  test/simpleTestForGenerator/CC-BY-3.0-NL.txt
  test/simpleTestForGenerator/CC-BY-NC-SA-2.0-FR.txt
Labels: new license/exception request, new license/exception: Accepted

#1291 Add CC-BY-NC-SA-2.0-UK license
  src/CC-BY-NC-SA-2.0-UK.xml
  test/simpleTestForGenerator/CC-BY-NC-SA-2.0-UK.txt
Labels: new license/exception request, new license/exception: Accepted

#1302 Update Internet Systems Consortium (ISC) license
  src/ISC.xml
Labels: XML markup change

#1300 Improve `DOCS/new-license-workflow.md`
  DOCS/new-license-workflow.md
Labels: documentation

#1297 0BSD: add markup for (optional) title
  src/0BSD.xml
Labels: XML markup change

#1314 Add release notes for 3.14
  RELEASE-NOTES.md
Labels: documentation

#1317 Add new URL for the Q Public License (QPL-1.0)
  src/QPL-1.0.xml
Labels: minor updates to file
