Repository spdx/license-list-XML, pull requests merged in 2022-02, with the labels that each got.

#1391 Add Jam license
  src/Jam.xml
  test/simpleTestForGenerator/Jam.txt
Labels: new license/exception request, new license/exception: Accepted

#1360 Spencer-94 - add markup
  src/Spencer-94.xml
Labels: XML markup change

#1411 bzip2-1.0.5: deprecate
  src/bzip2-1.0.5.xml
Labels: XML markup change

#1412 Add release notes for 3.16
  RELEASE-NOTES.md
Labels: documentation

#1415 New License: Arphic-1999
  src/Arphic-1999.xml
  test/simpleTestForGenerator/Arphic-1999.txt
Labels: new license/exception request, new license/exception: Accepted
