Repository spdx/license-list-XML, pull requests merged in 2022-11, with the labels that each got.

#1692 Overhaul FAQ
  DOCS/faq.md
Labels: documentation

#1693 add link to FAQ
  README.md
Labels: documentation

#1687 Improve notes for `GPL-x.0-only` and `GPL-x.0-or-later`
  src/GPL-1.0-only.xml
  src/GPL-1.0-or-later.xml
  src/GPL-2.0-only.xml
  src/GPL-2.0-or-later.xml
  src/GPL-3.0-only.xml
  src/GPL-3.0-or-later.xml
Labels: minor updates to file

#1700 Add "and" and "&" to the equivalent words list
  equivalentwords.txt
Labels: XML markup change

#1708 Fix #1662 Deprecated licences used in exceptions description
  src/exceptions/389-exception.xml
  src/exceptions/Autoconf-exception-2.0.xml
  src/exceptions/Autoconf-exception-3.0.xml
  src/exceptions/Bison-exception-2.2.xml
  src/exceptions/CLISP-exception-2.0.xml
  src/exceptions/DigiRule-FOSS-exception.xml
  src/exceptions/FLTK-exception.xml
  src/exceptions/Font-exception-2.0.xml
  src/exceptions/GCC-exception-2.0.xml
  src/exceptions/GCC-exception-3.1.xml
  src/exceptions/OCCT-exception-1.0.xml
  src/exceptions/PS-or-PDF-font-exception-20170817.xml
  src/exceptions/Qt-LGPL-exception-1.1.xml
  src/exceptions/WxWindows-exception-3.1.xml
  src/exceptions/eCos-exception-2.0.xml
  src/exceptions/i2p-gpl-java-exception.xml
  src/exceptions/mif-exception.xml
  src/exceptions/u-boot-exception-2.0.xml
Labels: minor updates to file

#1701 New License: Knuth-CTAN
  src/Knuth-CTAN.xml
  test/simpleTestForGenerator/Knuth-CTAN.txt
Labels: new license/exception request, new license/exception: Accepted

#1702 New License: libutil-David-Nugent
  src/libutil-David-Nugent.xml
  test/simpleTestForGenerator/libutil-David-Nugent.txt
Labels: new license/exception request, new license/exception: Accepted

#1703 Update BSD-3-Clause to add Note
  src/BSD-3-Clause.xml
Labels: minor updates to file

#1699 Remove spacing around philicenses alt text
  expected-warnings
  src/GPL-3.0-only.xml
Labels: technical issue

#1704 Beerware: add markup to email address
  src/Beerware.xml
Labels: XML markup change

#1726 Add docs on release process
  DOCS/release-process.md
Labels: documentation

#1727 Add release notes for 3.19
  RELEASE-NOTES.md
Labels: documentation
