Repository spdx/license-list-XML, pull requests merged in 2022-08, with the labels that each got.

#1547 Add CC-BY-3.0-IGO
  src/CC-BY-3.0-IGO.xml
  test/simpleTestForGenerator/CC-BY-3.0-IGO.txt
Labels: new license/exception request, new license/exception: Accepted

#1549 New license: Python-2.0.1
  src/Python-2.0.1.xml
  src/Python-2.0.xml
  test/simpleTestForGenerator/Python-2.0.1.txt
Labels: new license/exception request, new license/exception: Accepted

#1563 Add mpi-permissive
  src/mpi-permissive.xml
  test/simpleTestForGenerator/mpi-permissive.txt
Labels: new license/exception request, new license/exception: Accepted

#1564 Add markup to mpich2
  src/mpich2.xml
  test/simpleTestForGenerator/mpich2.txt
Labels: XML markup change

#1576 Add release notes for 3.18
  RELEASE-NOTES.md
Labels: documentation

#1580 Conforming edits for main branch name change
  .github/workflows/deploy.yaml
  .github/workflows/validate.yaml
  CONTRIBUTING.md
  DOCS/faq.md
  DOCS/git-usage.md
  DOCS/new-license-workflow.md
Labels: technical issue

#1581 MIT-CMU: Adding optional "prior" permission
  src/MIT-CMU.xml
  test/simpleTestForGenerator/MIT-CMU.txt
Labels: XML markup change

#1587 Fix Alt regular expression in HPND
  src/HPND.xml
Labels: XML markup change

#1589 Remove extraneous line at the end of the fair text file
  test/simpleTestForGenerator/Fair.txt
Labels: XML markup change

#1592 Remove extraneous quote from gnu-javamail-exception test file
  test/simpleTestForGenerator/gnu-javamail-exception.txt
Labels: minor updates to file

#1599 Remove extraneous comma from SugarCrM-1.1.3
  src/SugarCRM-1.1.3.xml
Labels: XML markup change

#1595 Fix matching error to original license for CPAL-1.0
  src/CPAL-1.0.xml
Labels: minor updates to file
