Repository spdx/license-list-XML, pull requests merged in 2022-04, with the labels that each got.

#1425 Add GPL-3.0 text as optional for LGPL-3.0 licenses
  expected-warnings
  src/LGPL-3.0+.xml
  src/LGPL-3.0-only.xml
  src/LGPL-3.0-or-later.xml
  src/LGPL-3.0.xml
  test/simpleTestForGenerator/LGPL-3.0-only.txt
  test/simpleTestForGenerator/LGPL-3.0-or-later.txt
  test/simpleTestForGenerator/LGPL-3.0.txt
Labels: XML markup change

#1433 Fix minor typo in LGPL-3.0-linking-exception
  src/exceptions/LGPL-3.0-linking-exception.xml
Labels: minor updates to file

#1447 Add documentation on checking for duplicate licenses
  DOCS/new-license-workflow.md
Labels: documentation
