Repository spdx/license-list-XML, pull requests merged in 2022-12, with the labels that each got.

#1733 New License: Symlinks
  src/Symlinks.xml
  test/simpleTestForGenerator/Symlinks.txt
Labels: new license/exception request, new license/exception: Accepted

#1728 HPND: add markup
  src/HPND.xml
Labels: XML markup change

#1709 Fix formatting of Artistic-1.0-cl8
  src/Artistic-1.0-cl8.xml
Labels: minor updates to file

#1740 New License: LOOP
  src/LOOP.xml
  test/simpleTestForGenerator/LOOP.txt
Labels: new license/exception request, new license/exception: Accepted

#1742 Fix validation with switch to Python xml validator
  .github/workflows/validate.yaml
  package.json
  requirements.txt
  validate-schema.js
  validate-schema.py
Labels: technical issue

#1710 StandardML-NJ.xml: fix URL
  src/StandardML-NJ.xml
Labels: XML markup change

#1711 LGPL-2.1+.xml: fix license name
  src/LGPL-2.1+.xml
Labels: XML markup change

#1750 New License: IJG-short
  src/IJG-short.xml
  test/simpleTestForGenerator/IJG-short.txt
Labels: new license/exception request, new license/exception: Accepted

#1747 New License: Graphics-Gems
  src/Graphics-Gems.xml
  test/simpleTestForGenerator/Graphics-Gems.txt
Labels: new license/exception request, new license/exception: Accepted

#1749 New License: Bitstream-Charter
  src/Bitstream-Charter.xml
  test/simpleTestForGenerator/Bitstream-Charter.txt
Labels: new license/exception request, new license/exception: Accepted

#1753 Add MIT-Wu
  src/MIT-Wu.xml
  test/simpleTestForGenerator/MIT-Wu.txt
Labels: new license/exception request, new license/exception: Accepted

#1754 New License: TTWL
  src/TTWL.xml
  test/simpleTestForGenerator/TTWL.txt
Labels: new license/exception request, new license/exception: Accepted

#1745 Update request new license doc
  DOCS/request-new-license.md
Labels: documentation

#1755 Hyperlink to SPDX Matching Guidelines
  DOCS/license-inclusion-principles.md
Labels: documentation

#1757 Fix link in license inclusion principles
  DOCS/license-inclusion-principles.md
Labels: documentation

#1761 Improve efficiency of test-one-license
  test-one-license
Labels: technical issue

#1763 docs: xml-fields: Explain optional tag spacing=none
  DOCS/xml-fields.md
Labels: documentation

#1759 Add HPND-export-US
  src/HPND-export-US.xml
  test/simpleTestForGenerator/HPND-export-US.txt
Labels: new license/exception request, new license/exception: Accepted

#1764 NTP: Add optional 'of' text
  src/NTP.xml
Labels: XML markup change

#1766 BSD-3-Clause: expand markup
  src/BSD-3-Clause.xml
Labels: XML markup change
