Repository spdx/license-list-XML, pull requests merged in 2022-09, with the labels that each got.

#1615 Removing 0BSD license from Python 2.0.1 test file
  test/simpleTestForGenerator/Python-2.0.1.txt
Labels: minor updates to file

#1593 Fix APSL-2.0 exhibit text to match test code
  src/APSL-2.0.xml
Labels: minor updates to file

#1594 Fix matching problem for APL-1.0.xml
  src/APL-1.0.xml
Labels: minor updates to file

#1597 Fix OSET-PL-2.1 matching issue
  src/OSET-PL-2.1.xml
Labels: minor updates to file

#1596 Remove extraneous > from MPL-2.0-no-copyleft-exception
  src/MPL-2.0-no-copyleft-exception.xml
Labels: minor updates to file

#1598 Match test text or SPL-1.0
  src/SPL-1.0.xml
Labels: minor updates to file

#1584 HPND-sell-variant: add XML markup
  src/HPND-sell-variant.xml
Labels: XML markup change

#1588 Fix alt regex pattern in HPND-sell-variant
  src/HPND-sell-variant.xml
Labels: XML markup change

#1619 Remove extra line in Spencer-86 test file
  test/simpleTestForGenerator/Spencer-86.txt
Labels: XML markup change

#1623 Add info on full name of license
  DOCS/license-fields.md
Labels: documentation

#1626 Fix typo
  CONTRIBUTING.md
Labels: documentation

#1618 Add license: checkmk
  src/checkmk.xml
  test/simpleTestForGenerator/checkmk.txt
Labels: new license/exception request, new license/exception: Accepted

#1630 add markup to BSD-4-Clause
  src/BSD-4-Clause.xml
Labels: XML markup change

#1628 Add mark-up to BSD-3-Clause
  src/BSD-3-Clause.xml
Labels: XML markup change

#1573 Update License-fields.md
  DOCS/license-fields.md
Labels: documentation

#1542 Delete matching-guidelines
  DOCS/matching-guidelines
Labels: documentation

#1641 faq: update to lates identifiers
  DOCS/faq.md
Labels: documentation
