Repository spdx/license-list-XML, pull requests merged in 2022-07, with the labels that each got.

#1449 Add GStreamer exception to the GPL
  src/exceptions/GStreamer-exception-2005.xml
  src/exceptions/GStreamer-exception-2008.xml
  test/simpleTestForGenerator/GStreamer-exception-2005.txt
  test/simpleTestForGenerator/GStreamer-exception-2008.txt
Labels: new license/exception: Accepted

#1526 New License: Minpack
  src/Minpack.xml
  test/simpleTestForGenerator/Minpack.txt
Labels: new license/exception: Accepted

#1517 Add new license: MS-LPL
  src/MS-LPL.xml
  test/simpleTestForGenerator/MS-LPL.txt
Labels: new license/exception: Accepted

#1530 Update faq.md
  DOCS/faq.md
Labels: documentation

#1540 Update 389-exception - add url
  src/exceptions/389-exception.xml
Labels: minor updates to file

#1546 Add NICTA-1.0
  src/NICTA-1.0.xml
  test/simpleTestForGenerator/NICTA-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1538 Add LZMA licenses
  src/LZMA-SDK-9.11-to-9.20.xml
  src/LZMA-SDK-9.22.xml
  test/simpleTestForGenerator/LZMA-SDK-9.11-to-9.20.txt
  test/simpleTestForGenerator/LZMA-SDK-9.22.txt
Labels: new license/exception request, new license/exception: Accepted
