Repository spdx/license-list-XML, pull requests merged in 2022-05, with the labels that each got.

#1446 SMLNJ: add markup for template #1441
  expected-warnings
  src/SMLNJ.xml
Labels: XML markup change

#1423 New License: Bitstream-Vera
  src/Bitstream-Vera.xml
  test/simpleTestForGenerator/Bitstream-Vera.txt
Labels: new license/exception: Accepted

#1436 openvpn-openssl-exception: add markup
  src/exceptions/openvpn-openssl-exception.xml
Labels: XML markup change

#1455 APSL-2.0: Add standard license header tags
  src/APSL-2.0.xml
Labels: XML markup change

#1456 Add release notes for 3.17
  RELEASE-NOTES.md
Labels: documentation

#1459 Update README
  README.md
Labels: documentation

#1460 Update DOCS readme to add missing links
  DOCS/README.md
Labels: documentation

#1458 Create license-decision-template.md
  DOCS/license-decision-template.md
Labels: documentation
