Repository spdx/license-list-XML, pull requests merged in 2022-03, with the labels that each got.

#1416 Making 'Creative Commons Notice' optional
  src/CC-BY-3.0.xml
Labels: XML markup change

#1421 New License: Baekmuk
  src/Baekmuk.xml
  test/simpleTestForGenerator/Baekmuk.txt
Labels: new license/exception: Accepted

#1420 New License: mplus
  src/mplus.xml
  test/simpleTestForGenerator/mplus.txt
Labels: new license/exception: Accepted

#1431 Update Jam - OSI-approved
  src/Jam.xml
Labels: minor updates to file

#1424 Add KiCad Libraries Exception
  src/exceptions/KiCad-libraries-exception.xml
  test/simpleTestForGenerator/KiCad-libraries-exception.txt
Labels: new license/exception: Accepted

#1427 Update new-license-workflow.md
  DOCS/new-license-workflow.md
Labels: documentation

#1435 Align review template to inclusion principles
  DOCS/submission-response-template.md
Labels: documentation

#1434 KiCad-libraries-exception: Add note on base license
  src/exceptions/KiCad-libraries-exception.xml
Labels: minor updates to file
