Repository spdx/license-list-XML, pull requests merged in 2022-10, with the labels that each got.

#1665 Revise templates, README
  DOCS/README.md
  DOCS/license-decision-template.md
  DOCS/submission-response-template.md
  DOCS/template-decision.md
  DOCS/template-license-review-checklist.md
Labels: documentation

#1649 Update faq.md
  DOCS/faq.md
Labels: documentation

#1666 Fix broken links
  DOCS/request-new-license.md
Labels: documentation

#1674 Fix misplaced /item in CDDL-1.0
  src/CDDL-1.0.xml
Labels: minor updates to file

#1675 Replace GPL-2.0+ by GPL-2.0-or-later.
  src/exceptions/GCC-exception-2.0.xml
Labels: minor updates to file

#1679 Update FAQ - What question
  DOCS/faq.md
Labels: documentation

#1678 New exception: x11vnc-opensel-exception
  src/exceptions/x11vnc-openssl-exception.xml
  test/simpleTestForGenerator/x11vnc-openssl-exception.txt
Labels: new license/exception request, new license/exception: Accepted

#1670 Update README.md
  DOCS/README.md
Labels: documentation

#1660 New License: FSFULLRWD
  src/FSFULLRWD.xml
  test/simpleTestForGenerator/FSFULLRWD.txt
Labels: new license/exception request, new license/exception: Accepted

#1677 Add documentation on XML templates and fields
  DOCS/xml-fields.md
Labels: documentation

#1689 Add link to XML template fields docs
  DOCS/README.md
Labels: documentation

#1685 License Inclusion Principles - add ordered list
  DOCS/license-inclusion-principles.md
Labels: documentation
