Repository spdx/license-list-XML, pull requests merged in 2023-01, with the labels that each got.

#1767 fix formatting
  DOCS/request-new-license.md
Labels: documentation

#1769 New License: CC-BY-NC-SA-2.0-DE.xml
  src/CC-BY-NC-SA-2.0-DE.xml
  test/simpleTestForGenerator/CC-BY-NC-SA-2.0-DE.txt
Labels: new license/exception request, new license/exception: Accepted

#1698 Create history.md
  DOCS/history.md
Labels: documentation

#1772 Update request-new-license.md
  DOCS/request-new-license.md
Labels: documentation

#1792 Add varietal spellings of merchantability
  equivalentwords.txt
Labels: XML markup change
