Repository spdx/license-list-XML, pull requests merged in 2023-11, with the labels that each got.

#2222 Revise FSFAP.xml to accommodate variant final sentence
  src/FSFAP.xml
Labels: XML markup change

#2237 Revise HPND to accommodate plural variant
  src/HPND.xml
Labels: XML markup change, HPND-variant

#2240 Revise HPND-sell-variant to accommodate variant with plural licensors
  src/HPND-sell-variant.xml
Labels: XML markup change, HPND-variant

#2231 new license: hdparm
  src/hdparm.xml
  test/simpleTestForGenerator/hdparm.txt
Labels: new license/exception: Accepted, used in major distro

#2230 new license: AML-glslang
  src/AML-glslang.xml
  test/simpleTestForGenerator/AML-glslang.txt
Labels: new license/exception: Accepted, used in major distro

#2247 new license: Pixar License
  src/Pixar.xml
  test/simpleTestForGenerator/Pixar.txt
Labels: new license/exception: Accepted, used in major distro

#2207 Add DRL-1.1
  src/DRL-1.1.xml
  test/simpleTestForGenerator/DRL-1.1.txt
Labels: new license/exception: Accepted

#2246 markup change for FSFULLRWD
  src/FSFULLRWD.xml
Labels: XML markup change

#2248 new license: HPND-sell-MIT-disclaimer-xserver
  src/HPND-sell-MIT-disclaimer-xserver.xml
  test/simpleTestForGenerator/HPND-sell-MIT-disclaimer-xserver.txt
Labels: new license/exception: Accepted, used in major distro

#2249 new license: DEC-3-Clause
  src/DEC-3-Clause.xml
  test/simpleTestForGenerator/DEC-3-Clause.txt
Labels: new license/exception: Accepted, used in major distro

#2250 new license: Adobe-Display-PostScript
  src/Adobe-Display-PostScript.xml
  test/simpleTestForGenerator/Adobe-Display-PostScript.txt
Labels: new license/exception: Accepted, used in major distro

#2251 new license: GCR-docs
  src/GCR-docs.xml
  test/simpleTestForGenerator/GCR-docs.txt
Labels: new license/exception: Accepted, used in major distro

#2253 new license: radvd
  src/radvd.xml
  test/simpleTestForGenerator/radvd.txt
Labels: new license/exception: Accepted, used in major distro

#2254 new license: SAX-PD-2.0
  src/SAX-PD-2.0.xml
  test/simpleTestForGenerator/SAX-PD-2.0.txt
Labels: new license/exception: Accepted, used in major distro

#2258 Fixes broken link to CONTRIBUTING in DOCS
  DOCS/README.md
Labels: documentation

#2257 Fix python-ldap license link
  src/python-ldap.xml
Labels: minor updates to file
