Repository spdx/license-list-XML, pull requests merged in 2023-04, with the labels that each got.

#1910 FSFULLRWD: remove line break in the name attribute
  src/FSFULLRWD.xml
Labels: XML markup change

#1915 New License: NIST-Software
  src/NIST-Software.xml
  test/simpleTestForGenerator/NIST-Software.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1927 Add UnixCrypt license
  src/UnixCrypt.xml
  test/simpleTestForGenerator/UnixCrypt.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1928 Add MIT-Festival license
  src/MIT-Festival.xml
  test/simpleTestForGenerator/MIT-Festival.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1909 Accept any copyright holders in BSD-4.3TAHOE
  src/BSD-4.3TAHOE.xml
Labels: XML markup change

#1933 New exception: vsftpd-openssl-exception
  src/exceptions/vsftpd-openssl-exception.xml
  test/simpleTestForGenerator/vsftpd-openssl-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1920 fix: add missing period
  src/AGPL-3.0-only.xml
Labels: minor updates to file

#1918 Unicode urls
  src/Unicode-DFS-2016.xml
  src/Unicode-TOU.xml
Labels: minor updates to file

#1916 added line break in Spencer-86
  src/Spencer-86.xml
Labels: minor updates to file

#1873 HPND-sell-variant-MIT-disclaimer - add line breaks
  src/HPND-sell-variant-MIT-disclaimer.xml
Labels: minor updates to file

#1871 OFFIS: adding missing p tags
  src/OFFIS.xml
Labels: minor updates to file

#1932 New license: Latex2e-translated-notice
  src/Latex2e-translated-notice.xml
  test/simpleTestForGenerator/Latex2e-translated-notice.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1930 Add OLFL-1.3
  src/OLFL-1.3.xml
  test/simpleTestForGenerator/OLFL-1.3.txt
Labels: new license/exception request, new license/exception: Accepted

#1937 Grammatical Error in Getting Started Section
  CONTRIBUTING.md
Labels: documentation

#1945 Add metamail License
  src/metamail.xml
  test/simpleTestForGenerator/metamail.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1877 New License: SGP4
  src/SGP4.xml
  test/simpleTestForGenerator/SGP4.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1940 Add CC-BY-SA-3.0-IGO
  src/CC-BY-SA-3.0-IGO.xml
  test/simpleTestForGenerator/CC-BY-SA-3.0-IGO.txt
Labels: new license/exception request, new license/exception: Accepted

#1914 XML guidance: add specific tags for <>
  DOCS/xml-fields.md
Labels: documentation
