Repository spdx/license-list-XML, pull requests merged in 2023-05, with the labels that each got.

#1956 New license request: ASWF Digital Assets License 1.0
  src/ASWF-Digital-Assets-1.0.xml
  test/simpleTestForGenerator/ASWF-Digital-Assets-1.0.txt
Labels: new license/exception request, new license/exception: Accepted

#1938 AGPL-3.0: Add missing period in standard license header
  src/AGPL-3.0.xml
Labels: minor updates to file

#1961 New License: Xfig
  src/Xfig.xml
  test/simpleTestForGenerator/Xfig.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1952 New License: TermReadKey
  src/TermReadKey.xml
  test/simpleTestForGenerator/TermReadKey.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1951 Update template-decision.md to add reference to next steps
  DOCS/template-decision.md
Labels: documentation

#1964 Document what is not allowed in alt and optional tags
  DOCS/xml-fields.md
Labels: documentation

#1913 New License: Xdebug
  src/Xdebug-1.03.xml
  test/simpleTestForGenerator/Xdebug-1.03.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1968 New exception: Linux-man-pages-one-para
  src/Linux-man-pages-one-para.xml
  test/simpleTestForGenerator/Linux-man-pages-one-para.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1950 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1970 New exception: GPL-3.0-interface-exception
  src/exceptions/GPL-3.0-interface-exception.xml
  test/simpleTestForGenerator/GPL-3.0-interface-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro
