Repository spdx/license-list-XML, pull requests merged in 2023-09, with the labels that each got.

#2099 Add DL-DE-ZERO-2.0
  src/DL-DE-ZERO-2.0.xml
  test/simpleTestForGenerator/DL-DE-ZERO-2.0.txt
Labels: new license/exception request, new license/exception: Accepted

#2084 Modify BSD-3-Clause markup to cover IBM variant with 'Neither the names'
  src/BSD-3-Clause.xml
Labels: XML markup change

#2101 correct lower/uppercase w in MMIXware
  src/MMIXware.xml
Labels: minor updates to file

#2116 new license: MPEG-Software-Simulation
  src/MPEG-Software-Simulation.xml
  test/simpleTestForGenerator/MPEG-Software-Simulation.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2103 allow Libtool-exception to be exception to any license
  src/MPEG-Software-Simulation.xml
  test/simpleTestForGenerator/MPEG-Software-Simulation.txt
Labels: XML markup change

#2126 New license: pnmstitch
  src/pnmstitch.xml
  test/simpleTestForGenerator/pnmstitch.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2062 Update MIT-testregex.xml
  src/MIT-testregex.xml
Labels: minor updates to file

#2096 extend x11vnc OpenSSL Exception markup to match similar exceptions
  src/exceptions/x11vnc-openssl-exception.xml
Labels: XML markup change

#2122 Update GPL-3.0-linking-source-exception.xml - markup
  src/exceptions/GPL-3.0-linking-source-exception.xml
Labels: XML markup change

#2094 Add markup: Crossword.xml
  src/Crossword.xml
  test/simpleTestForGenerator/Crossword.txt
Labels: XML markup change

#2107 extend markup of BSD-3-Clause
  src/BSD-3-Clause.xml
Labels: XML markup change

#2111 Update new-license-request.yaml
  .github/ISSUE_TEMPLATE/new-license-request.yaml
Labels: documentation

#2131 Small corrections in NPL-1.0 text
  src/NPL-1.0.xml
  test/simpleTestForGenerator/NPL-1.0.txt
Labels: minor updates to file

#2130 allow Libtool-exception to be exception to GNU Lesser General Public …
  src/exceptions/Libtool-exception.xml
Labels: XML markup change

#2129 change identifier from MPEG-Software-Simulation to MPEG-SSG
  src/MPEG-SSG.xml
  test/simpleTestForGenerator/MPEG-SSG.txt
Labels: minor updates to file

#2133 Add BSD-3-Clause-Sun license
  src/BSD-3-Clause-Sun.xml
  test/simpleTestForGenerator/BSD-3-Clause-Sun.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2135 Add FBM license
  src/FBM.xml
  test/simpleTestForGenerator/FBM.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2136 Add BSD-Systemic license
  src/BSD-Systemics.xml
  test/simpleTestForGenerator/BSD-Systemics.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2108 extend markup of openvpn-openssl-exception to accomodate psycopg2 ope…
  src/exceptions/openvpn-openssl-exception.xml
Labels: XML markup change

#2137 Fix spacing in new-license-request.yaml
  .github/ISSUE_TEMPLATE/new-license-request.yaml
Labels: technical issue

#2110 Fix license URL of Ruby
  src/Ruby.xml
Labels: minor updates to file

#2114 Update BSD-Attribution-HPND-disclaimer.xml - markup
  src/BSD-Attribution-HPND-disclaimer.xml
Labels: XML markup change

#2113 Update HPND.xml - add markup
  src/HPND.xml
  test/simpleTestForGenerator/HPND.txt
Labels: XML markup change

#2143 HPND: Fix appear/apears alternation
  src/HPND.xml
Labels: XML markup change

#2149 new license: swrule
  src/swrule.xml
  test/simpleTestForGenerator/swrule.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2150 new license: ssh-keyscan
  src/ssh-keyscan.xml
  test/simpleTestForGenerator/ssh-keyscan.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2151 new license: BSD-Inferno-Nettverk
  src/BSD-Inferno-Nettverk.xml
  test/simpleTestForGenerator/BSD-Inferno-Nettverk.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2146 new license: HPND-Pbmplus
  src/HPND-Pbmplus.xml
  test/simpleTestForGenerator/HPND-Pbmplus.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro, HPND-variant

#2148 new license: Cronyx
  src/Cronyx.xml
  test/simpleTestForGenerator/Cronyx.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2147 new license: Lucida-Bitmap-Fonts
  src/Lucida-Bitmap-Fonts.xml
  test/simpleTestForGenerator/Lucida-Bitmap-Fonts.txt
Labels: new license/exception: Accepted, used in major distro

#2153 new license: HPND-sell-regexpr
  src/HPND-sell-regexpr.xml
  test/simpleTestForGenerator/HPND-sell-regexpr.txt
Labels: new license/exception: Accepted, used in major distro, HPND-variant

#2112 Update HPND-sell-variant.xml - optional comma
  src/HPND-sell-variant.xml
Labels: XML markup change

#2139 New License: fwlw
  src/fwlw.xml
  test/simpleTestForGenerator/fwlw.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2145 New License: magaz
  src/magaz.xml
  test/simpleTestForGenerator/magaz.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2144 New License: ulem
  src/ulem.xml
  test/simpleTestForGenerator/ulem.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2154 New License: Furuseth
  src/Furuseth.xml
  test/simpleTestForGenerator/Furuseth.txt
Labels: new license/exception: Accepted, used in major distro

#2156 new license: Kastrup
  src/Kastrup.xml
  test/simpleTestForGenerator/Kastrup.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2161 new license: SGI-OpenGL
  src/SGI-OpenGL.xml
  test/simpleTestForGenerator/SGI-OpenGL.txt
Labels: new license/exception: Accepted, used in major distro

#2157 new exception: UBDL-exception
  src/exceptions/UBDL-exception.xml
  test/simpleTestForGenerator/UBDL-exception.txt
Labels: new license/exception: Accepted, used in major distro

#2158 new license: McPhee-slideshow
  src/McPhee-slideshow.xml
  test/simpleTestForGenerator/McPhee-slideshow.txt
Labels: new license/exception: Accepted, used in major distro

#2170 Add HPND-export-US-modify
  src/HPND-export-US-modify.xml
  test/simpleTestForGenerator/HPND-export-US-modify.txt
Labels: new license/exception: Accepted, used in major distro, HPND-variant

#2175 new license: Adobe-Utopia
  src/Adobe-Utopia.xml
  test/simpleTestForGenerator/Adobe-Utopia.txt
Labels: new license/exception: Accepted, used in major distro

#2181 new license: lsof
  src/lsof.xml
  test/simpleTestForGenerator/lsof.txt
Labels: new license/exception request, new license/exception: Accepted

#2188 new license: python-ldap
  src/python-ldap.xml
  test/simpleTestForGenerator/python-ldap.txt
Labels: new license/exception: Accepted

#2174 add markup to BSD-4.3RENO.xml
  src/BSD-4.3RENO.xml
Labels: XML markup change

#2171 Update Note for HPND-Pbmplus.xml
  src/HPND-Pbmplus.xml
Labels: minor updates to file

#2172 Add markup to GCC-exception-2.0.xml
  src/exceptions/GCC-exception-2.0.xml
Labels: XML markup change

#2061 New License: BSD-3-Clause-HP
  src/BSD-3-Clause-HP.xml
  test/simpleTestForGenerator/BSD-3-Clause-HP.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1923 AGPL-1.0: fix typo in Notes field
  src/AGPL-1.0.xml
Labels: minor updates to file

#2187 new license: PDAL
  src/PADL.xml
  test/simpleTestForGenerator/PADL.txt
Labels: new license/exception: Accepted, used in major distro

#2184 new license: HPND-doc-sell
  src/HPND-doc-sell.xml
  test/simpleTestForGenerator/HPND-doc-sell.txt
Labels: new license/exception: Accepted, used in major distro

#2185 new license: HPND-doc
  src/HPND-doc.xml
  test/simpleTestForGenerator/HPND-doc.txt
Labels: new license/exception: Accepted, used in major distro, HPND-variant
