Repository spdx/license-list-XML, pull requests merged in 2023-02, with the labels that each got.

#1814 New License: w3m
  src/w3m.xml
  test/simpleTestForGenerator/w3m.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1815 New License: CFITSIO
  src/CFITSIO.xml
  test/simpleTestForGenerator/CFITSIO.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1748 New License: SunPro
  src/SunPro.xml
  test/simpleTestForGenerator/SunPro.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1801 Update references now that the spec has been reorganized
  README.md
Labels: documentation

#1825 New License: BSD-4.3TAHOE
  src/BSD-4.3TAHOE.xml
  test/simpleTestForGenerator/BSD-4.3TAHOE.txt
Labels: new license/exception: Accepted

#1824 New License: CMU-Mach
  src/CMU-Mach.xml
  test/simpleTestForGenerator/CMU-Mach.txt
Labels: new license/exception request, new license/exception: Accepted

#1823 New License: snprintf
  src/snprintf.xml
  test/simpleTestForGenerator/snprintf.txt
Labels: new license/exception request, new license/exception: Accepted

#1822 New License: xlock
  src/xlock.xml
  test/simpleTestForGenerator/xlock.txt
Labels: new license/exception request, new license/exception: Accepted

#1800 Use relative Markdown links for stuff stored in this repo
  CONTRIBUTING.md
  DOCS/faq.md
  DOCS/history.md
  DOCS/new-license-workflow.md
  DOCS/release-process.md
  DOCS/request-new-license.md
  DOCS/xml-fields.md
  README.md
  RELEASE-NOTES.md
Labels: documentation

#1793 New License: OFFIS
  src/OFFIS.xml
  test/simpleTestForGenerator/OFFIS.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1794 New License: UCAR
  src/UCAR.xml
  test/simpleTestForGenerator/UCAR.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1802 New License: BSD-4.3RENO
  src/BSD-4.3RENO.xml
  test/simpleTestForGenerator/BSD-4.3RENO.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1820 New License: HP-1986
  src/HP-1986.xml
  test/simpleTestForGenerator/HP-1986.txt
Labels: new license/exception: Accepted, used in major distro

#1819 New License: Martin-Birgmeier
  src/Martin-Birgmeier.xml
  test/simpleTestForGenerator/Martin-Birgmeier.txt
Labels: new license/exception: Accepted, used in major distro

#1813 New License: Kazlib
  src/Kazlib.xml
  test/simpleTestForGenerator/Kazlib.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1804 New exception: SWI-exception
  src/exceptions/SWI-exception.xml
  test/simpleTestForGenerator/SWI-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1803 New License: JPL-image
  src/JPL-image.xml
  test/simpleTestForGenerator/JPL-image.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1829 New License: HPND-sell-variant-MIT-disclaimer
  src/HPND-sell-variant-MIT-disclaimer.xml
  test/simpleTestForGenerator/HPND-sell-variant-MIT-disclaimer.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1818 New License: BSD-Advertising-Acknowledgement
  src/BSD-Advertising-Acknowledgement.xml
  test/simpleTestForGenerator/BSD-Advertising-Acknowledgement.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1661 New License: OpenPBS-2.3
  src/OpenPBS-2.3.xml
  test/simpleTestForGenerator/OpenPBS-2.3.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1807 New License: TPL-1.0
  src/TPL-1.0.xml
  test/simpleTestForGenerator/TPL-1.0.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1821 New exception: QPL-1.0-INRIA-2004-exception
  src/exceptions/QPL-1.0-INRIA-2004-exception.xml
  test/simpleTestForGenerator/QPL-1.0-INRIA-2004-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1811 FAQ heading improvements
  DOCS/faq.md
Labels: documentation

#1834 Add BSD-Attribution-HPND-disclaimer
  src/BSD-Attribution-HPND-disclaimer.xml
  test/simpleTestForGenerator/BSD-Attribution-HPND-disclaimer.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1833 Add Brian-Gladman-3-Clause
  src/Brian-Gladman-3-Clause.xml
  test/simpleTestForGenerator/Brian-Gladman-3-Clause.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1832 Add Clips license
  src/Clips.xml
  test/simpleTestForGenerator/Clips.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1831 Add GNAT-exception
  src/exceptions/GNAT-exception.xml
  test/simpleTestForGenerator/GNAT-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1830 Add HPND-Markus-Kuhn
  src/HPND-Markus-Kuhn.xml
  test/simpleTestForGenerator/HPND-Markus-Kuhn.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1835 Update FAQ: add link, other updates
  DOCS/faq.md
Labels: documentation

#1838 Add QPL-1.0-INRIA-2004
  src/QPL-1.0-INRIA-2004.xml
  test/simpleTestForGenerator/QPL-1.0-INRIA-2004.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1839 New License: IEC-Code-Components-EULA
  src/IEC-Code-Components-EULA.xml
  test/simpleTestForGenerator/IEC-Code-Components-EULA.txt
Labels: new license/exception request, new license/exception: Accepted

#1840 Add markup: Saxpath names
  src/Saxpath.xml
Labels: XML markup change

#1841 New License: Autoconf-exception-generic
  src/exceptions/Autoconf-exception-generic.xml
  test/simpleTestForGenerator/Autoconf-exception-generic.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1842 Update request-new-license.md
  DOCS/request-new-license.md
Labels: documentation

#1844 PSF-2.0: Add templating for related projects
  src/PSF-2.0.xml
Labels: XML markup change

#1845 Add Cornell-Lossless-JPEG
  src/Cornell-Lossless-JPEG.xml
  test/simpleTestForGenerator/Cornell-Lossless-JPEG.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1846 Add release notes for 3.20
  RELEASE-NOTES.md
Labels: documentation

#1848 Clean up extraneous files
  .gitignore
  .travis.yml
Labels: technical issue

#1850 New exception: Autoconf-exception-macro
  src/exceptions/Autoconf-exception-macro.xml
  test/simpleTestForGenerator/Autoconf-exception-macro.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1771 Add github issue template for new license
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-license-request.yaml
  .gitignore
Labels: discuss on legal call, documentation
