Repository spdx/license-list-XML, pull requests merged in 2023-06, with the labels that each got.

#1976 Address issue 1973
  src/exceptions/Classpath-exception-2.0.xml
Labels: XML markup change

#1998 Add ASWF-Digital-Assets-1.1
  src/ASWF-Digital-Assets-1.1.xml
  test/simpleTestForGenerator/ASWF-Digital-Assets-1.1.txt
Labels: new license/exception request, new license/exception: Accepted

#1994 Update LicenseListPublish to version 2.2.10
  Makefile
Labels: technical issue

#1997 Fix GPL URLs to use https
  test/simpleTestForGenerator/GPL-3.0-only.txt
  test/simpleTestForGenerator/GPL-3.0-or-later.txt
  test/simpleTestForGenerator/GPL-3.0.txt
Labels: minor updates to file

#1977 fix recent exceptions
  src/exceptions/cryptsetup-OpenSSL-exception.xml
  src/exceptions/libpri-OpenH323-exception.xml
Labels: minor updates to file

#1984 Add a version for the schema
  schema/ListedLicense.xsd
  schema/schema-version.md
Labels: XML schema change

#1980 Update JPL-image.xml: fix p tags
  src/JPL-image.xml
Labels: minor updates to file

#2005 Update Clips.xml to add missing p tag
  src/Clips.xml
Labels: minor updates to file

#2004 New exception: Asterisk-exception
  src/exceptions/Asterisk-exception.xml
  test/simpleTestForGenerator/Asterisk-exception.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2003 New License: Linux-man-pages-copyleft-var
  src/Linux-man-pages-copyleft-var.xml
  test/simpleTestForGenerator/Linux-man-pages-copyleft-var.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2002 New License: dtoa
  src/dtoa.xml
  test/simpleTestForGenerator/dtoa.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2000 New License: Linux-man-pages-copyleft-2-para
  src/Linux-man-pages-copyleft-2-para.xml
  test/simpleTestForGenerator/Linux-man-pages-copyleft-2-para.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1978 Update Linux-man-pages-1-para.xml
  src/Linux-man-pages-1-para.xml
  test/simpleTestForGenerator/Linux-man-pages-1-para.txt
Labels: minor updates to file

#2008 New License: OPL-UK-3.0 (second try)
  src/OPL-UK-3.0.xml
  test/simpleTestForGenerator/OPL-UK-3.0.txt
Labels: new license/exception request, new license/exception: Accepted

#2009 CI: update deploy.yaml to v3 actions
  .github/workflows/deploy.yaml
Labels: technical issue

#2010 CI: Add distribution for deploy setup-java
  .github/workflows/deploy.yaml
Labels: technical issue

#2007 New License: Inner-Net-2.0
  src/Inner-Net-2.0.xml
  test/simpleTestForGenerator/Inner-Net-2.0.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2014 LLGPL: Add fixed markup and test text
  src/exceptions/LLGPL.xml
  test/simpleTestForGenerator/LLGPL.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#1999 New License: Boehm-GC
  src/Boehm-GC.xml
  test/simpleTestForGenerator/Boehm-GC.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2015 Add release notes for 3.21
  RELEASE-NOTES.md
Labels: documentation
