Repository spdx/license-list-XML, pull requests merged in 2023-07, with the labels that each got.

#2021 Replace wrong placeholder in documentation
  DOCS/git-usage.md
Labels: documentation

#2031 add SL license
  src/SL.xml
  test/simpleTestForGenerator/SL.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2035 add check-cvs license
  src/check-cvs.xml
  test/simpleTestForGenerator/check-cvs.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2032 New License: Zeeff
  src/Zeeff.xml
  test/simpleTestForGenerator/Zeeff.txt
Labels: new license/exception request, used in major distro

#2051 Add HP-1989 license
  src/HP-1989.xml
  test/simpleTestForGenerator/HP-1989.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro

#2054 New License: Soundex
  src/Soundex.xml
  test/simpleTestForGenerator/Soundex.txt
Labels: new license/exception request, new license/exception: Accepted, used in major distro
