Repository spdx/license-list-XML, pull requests merged in 2024-09, with the labels that each got.

#2519 add Boehm-GC-without-fee
  src/Boehm-GC-without-fee.xml
  test/simpleTestForGenerator/Boehm-GC-without-fee.txt
Labels: new license/exception: Accepted, used in major distro

#2561 Update PSF-2.0.xml
  src/PSF-2.0.xml
Labels: minor updates to file

#2567 libutil-David-Nugent: Fix regex and spacing
  src/libutil-David-Nugent.xml
Labels: XML markup change
