Repository spdx/license-list-XML, pull requests merged in 2024-07, with the labels that each got.

#2520 add HIDAPI License
  src/HIDAPI.xml
  test/simpleTestForGenerator/HIDAPI.txt
Labels: new license/exception: Accepted, used in major distro

#2521 add Ruby-pty license
  src/Ruby-pty.xml
  test/simpleTestForGenerator/Ruby-pty.txt
Labels: new license/exception: Accepted, used in major distro

#2511 New License: X11-swapped
  src/X11-swapped.xml
  test/simpleTestForGenerator/X11-swapped.txt
Labels: new license/exception: Accepted

#2513 Adding markup to hpnd-export2-us
  src/HPND-export2-US.xml
Labels: XML markup change

#2509 New exception: Romic exception
  src/exceptions/romic-exception.xml
  test/simpleTestForGenerator/romic-exception.txt
Labels: new license/exception: Accepted

#2525 add HPND-Netrek
  src/HPND-Netrek.xml
  test/simpleTestForGenerator/HPND-Netrek.txt
Labels: new license/exception: Accepted, used in major distro

#2526 allow Antlr4 variant of BSD-3-Clause
  src/BSD-3-Clause.xml
Labels: XML markup change
