Repository spdx/license-list-XML, pull requests merged in 2024-03, with the labels that each got.

#2412 Update history.md
  DOCS/history.md
Labels: documentation

#2415 Update license-match.md - add links to matching doc
  DOCS/license-match.md
Labels: documentation

#2407 add markup to dtoa to allow AT&T holder as found in newlib package
  src/dtoa.xml
Labels: XML markup change

#2402 Adding markup to openvpn-openssl exception
  src/exceptions/openvpn-openssl-exception.xml
Labels: XML markup change

#2416 Update request-new-license.md
  DOCS/request-new-license.md
Labels: documentation

#2422 New License: xzoom
  src/xzoom.xml
  test/simpleTestForGenerator/xzoom.txt
Labels: new license/exception: Accepted, used in major distro

#2413 Update HPND-UC.xml NOTE to fix grammar
  src/HPND-UC.xml
Labels: minor updates to file

#2423 add OAR License
  src/OAR.xml
  test/simpleTestForGenerator/OAR.txt
Labels: new license/exception: Accepted, used in major distro
