Repository spdx/license-list-XML, pull requests merged in 2024-04, with the labels that each got.

#1901 Non printing characters
  test/simpleTestForGenerator/APL-1.0.txt
  test/simpleTestForGenerator/IBM-pibs.txt
  test/simpleTestForGenerator/NCGL-UK-2.0.txt
  test/simpleTestForGenerator/NPL-1.1.txt
  test/simpleTestForGenerator/OCCT-PL.txt
  test/simpleTestForGenerator/OGL-UK-1.0.txt
  test/simpleTestForGenerator/OSET-PL-2.1.txt
  test/simpleTestForGenerator/SHL-2.0.txt
  test/simpleTestForGenerator/SHL-2.1.txt
  test/simpleTestForGenerator/SISSL.txt
  test/simpleTestForGenerator/W3C-19980720.txt
Labels: minor updates to file

#2435 add BSD-2-clause-first-lines
  src/BSD-2-clause-first-lines.xml
  test/simpleTestForGenerator/BSD-2-clause-first-lines.txt
Labels: new license/exception: Accepted, used in major distro

#2437 add Sun-PPP-2000
  src/Sun-PPP-2000.xml
  test/simpleTestForGenerator/Sun-PPP-2000.txt
Labels: new license/exception: Accepted, used in major distro

#2444 fix typos in schema definition
  schema/ListedLicense.xsd
Labels: XML schema change

#2449 add markup change to cryptsetup-OpenSSL-exception
  src/exceptions/cryptsetup-OpenSSL-exception.xml
Labels: XML markup change

#2434 add NCL license
  src/NCL.xml
  test/simpleTestForGenerator/NCL.txt
Labels: new license/exception: Accepted, used in major distro

#2450 add HPND-UC-export-US license
  src/HPND-UC-export-US.xml
  test/simpleTestForGenerator/HPND-UC-export-US.txt
Labels: new license/exception: Accepted, used in major distro

#2448 add Catharon License
  src/Catharon.xml
  test/simpleTestForGenerator/Catharon.txt
Labels: new license/exception: Accepted, used in major distro

#2436 chore: update to actions/setup-python@v5
  .github/workflows/validate.yaml
Labels: technical issue
