Repository spdx/license-list-XML, pull requests merged in 2024-01, with the labels that each got.

#2194 New License: Unicode-3.0
  src/Unicode-3.0.xml
  test/simpleTestForGenerator/Unicode-3.0.txt
Labels: new license/exception: Accepted

#2267 Allow spaces in match for BSD-3-Clause
  src/BSD-3-Clause.xml
Labels: minor updates to file

#2265 Allow multiple spaces in MIT match
  src/MIT.xml
Labels: minor updates to file

#2281 new license: ISC-Veillard
  src/ISC-Veillard.xml
  test/simpleTestForGenerator/ISC-Veillard.txt
Labels: new license/exception: Accepted, used in major distro

#2300 New License: mailprio
  src/mailprio.xml
  test/simpleTestForGenerator/mailprio.txt
Labels: new license/exception: Accepted, used in major distro

#2297 Add note to SWI-exception
  src/exceptions/SWI-exception.xml
Labels: minor updates to file

#2235 Revise HPND-sell-variant to accommodate ungrammatical variant
  src/HPND-sell-variant.xml
Labels: XML markup change, HPND-variant

#2221 Revise FSFUL.xml to accommodate config.status variant
  src/FSFUL.xml
Labels: XML markup change

#2244 GPL-2.0-only: add other FSF url
  src/GPL-2.0-only.xml
Labels: minor updates to file

#2277 Addresses issue #2259
  src/Apache-1.0.xml
Labels: XML markup change

#2227 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2229 new license: BSD-Systemics-W3Works
  src/BSD-Systemics-W3Works.xml
  test/simpleTestForGenerator/BSD-Systemics-W3Works.txt
Labels: new license/exception: Accepted, used in major distro

#2279 Addresses issue #1972
  src/GPL-2.0+.xml
  src/GPL-2.0-only.xml
  src/GPL-2.0-or-later.xml
  src/GPL-2.0.xml
Labels: minor updates to file

#2309 add Bison-exception-1.24
  src/Bison-exception-1.24.xml
  test/simpleTestForGenerator/Bison-exception-1.24.txt
Labels: new license/exception: Accepted, used in major distro

#2218 BSD-3-Clause: Match IETF variant
  src/BSD-3-Clause.xml
Labels: XML markup change

#2304 Update Fair.xml to add webarchive URL
  src/Fair.xml
Labels: minor updates to file

#2298 Add markup to GNU-compiler-exception.xml
  src/exceptions/GNU-compiler-exception.xml
Labels: XML markup change

#2241 Add CC-BY-3.0-AU
  src/CC-BY-3.0-AU.xml
  test/simpleTestForGenerator/CC-BY-3.0-AU.txt
Labels: new license/exception: Accepted

#2301 Update Apache-1.1.xml to match original
  src/Apache-1.1.xml
  test/simpleTestForGenerator/Apache-1.1.txt
Labels: XML markup change, minor updates to file

#2312 SWI-exception: Revise notes
  src/exceptions/SWI-exception.xml
Labels: minor updates to file

#2311 Update Fair.xml to remove dodgy link
  src/Fair.xml
Labels: minor updates to file

#2306 Update template-decision.md
  DOCS/template-decision.md
Labels: documentation

#2327 add HPND-MIT-disclaimer
  src/HPND-MIT-disclaimer.xml
  test/simpleTestForGenerator/HPND-MIT-disclaimer.txt
Labels: new license/exception: Accepted, used in major distro, HPND-variant

#2328 add Caldera-no-preamble
  src/Caldera-no-preamble.xml
  test/simpleTestForGenerator/Caldera-no-preamble.txt
Labels: new license/exception: Accepted, used in major distro

#2331 Update MulanPSL-2.0.xml URL
  src/MulanPSL-2.0.xml
Labels: minor updates to file

#2329 add BSD-Source-beginning-file
  src/BSD-Source-beginning-file.xml
  test/simpleTestForGenerator/BSD-Source-beginning-file.txt
Labels: new license/exception: Accepted, used in major distro

#2310 New License: TGPPL-1.0
  src/TGPPL-1.0.xml
  test/simpleTestForGenerator/TGPPL-1.0.txt
Labels: new license/exception: Accepted, used in major distro

#2303 Remove standardLicenseHeader tag
  src/App-s2p.xml
  src/Arphic-1999.xml
  src/Baekmuk.xml
  src/Bitstream-Vera.xml
  src/mplus.xml
Labels: minor updates to file

#2296 Update xml-fields.md to add note re: spacing
  DOCS/xml-fields.md
Labels: documentation

#2338 Move exception to `exceptions`
  src/exceptions/Bison-exception-1.24.xml
Labels: minor updates to file

#2337 Add fmt-exception
  src/exceptions/fmt-exception.xml
  test/simpleTestForGenerator/fmt-exception.txt
Labels: new license/exception: Accepted, used in major distro

#2354 Add BSD-3-Clause-acpica
  src/BSD-3-Clause-acpica.xml
  test/simpleTestForGenerator/BSD-3-Clause-acpica.txt
Labels: new license/exception: Accepted, used in major distro

#2353 Update isOsiApproved in BlueOak-1.0.0.xml
  src/BlueOak-1.0.0.xml
Labels: XML markup change

#2351 Updated HPND-UC.xml to match graphviz tclhandle.c variant
  src/HPND-UC.xml
Labels: XML markup change

#2280 Fix markup for subsequent changes to CC-*-4.0 upstream text
  src/CC-BY-4.0.xml
  src/CC-BY-NC-4.0.xml
  src/CC-BY-NC-ND-4.0.xml
  src/CC-BY-NC-SA-4.0.xml
  src/CC-BY-ND-4.0.xml
  src/CC-BY-SA-4.0.xml
Labels: XML markup change
