Repository spdx/license-list-XML, pull requests merged in 2024-05, with the labels that each got.

#2464 Move matching guidelines
  DOCS/license-matching-guidelines-and-templates.md
Labels: documentation

#2447 Update W3C-20150513.xml
  src/W3C-20150513.xml
Labels: XML markup change

#2399 Update xml-fields.md
  DOCS/xml-fields.md
Labels: documentation

#2457 Add PPL
  src/PPL.xml
  test/simpleTestForGenerator/PPL.txt
Labels: new license/exception request, new license/exception: Accepted

#2466 Add PCRE2-exception
  src/exceptions/PCRE2-exception.xml
  test/simpleTestForGenerator/PCRE2-exception.txt
Labels: new license/exception: Accepted

#2465 mpich2: add note regarding project name change
  src/mpich2.xml
Labels: minor updates to file

#2440 Addresses issue #2430
  src/LGPL-2.0+.xml
  src/LGPL-2.0-only.xml
  src/LGPL-2.0-or-later.xml
  src/LGPL-2.0.xml
  src/LGPL-2.1+.xml
  src/LGPL-2.1-only.xml
  src/LGPL-2.1-or-later.xml
  src/LGPL-2.1.xml
  test/simpleTestForGenerator/LGPL-2.0-only.txt
  test/simpleTestForGenerator/LGPL-2.0-or-later.txt
  test/simpleTestForGenerator/LGPL-2.0.txt
  test/simpleTestForGenerator/LGPL-2.1-only.txt
  test/simpleTestForGenerator/LGPL-2.1-or-later.txt
  test/simpleTestForGenerator/LGPL-2.1.txt
  test/simpleTestForGenerator/depreciate_LGPL-2.0+.txt
  test/simpleTestForGenerator/depreciate_LGPL-2.1+.txt
Labels: minor updates to file

#2451 Addresses issue 2445 - CC-BY-3.0 template diverges from Creative Commons published text
  src/CC-BY-3.0.xml
  src/CC-BY-NC-3.0.xml
  src/CC-BY-NC-ND-3.0.xml
  src/CC-BY-NC-SA-3.0.xml
  src/CC-BY-ND-3.0.xml
  src/CC-BY-SA-3.0.xml
  test/simpleTestForGenerator/CC-BY-3.0.txt
  test/simpleTestForGenerator/CC-BY-NC-3.0.txt
  test/simpleTestForGenerator/CC-BY-NC-ND-3.0.txt
  test/simpleTestForGenerator/CC-BY-NC-SA-3.0.txt
  test/simpleTestForGenerator/CC-BY-ND-3.0.txt
  test/simpleTestForGenerator/CC-BY-SA-3.0.txt
Labels: minor updates to file

#2474 add HPND-export-US-acknowledgement
  src/HPND-export-US-acknowledgement.xml
  test/simpleTestForGenerator/HPND-export-US-acknowledgement.txt
Labels: new license/exception: Accepted, used in major distro

#2475 Create Asterisk-linking-protocols-exception.xml
  src/exceptions/Asterisk-linking-protocols-exception.xml
  test/simpleTestForGenerator/Asterisk-linking-protocols-exception.txt
Labels: new license/exception: Accepted

#2473 Update SMLNJ.xml to add optional "that"
  src/SMLNJ.xml
Labels: XML markup change

#2469 Update license-matching-guidelines-and-templates.md
  DOCS/license-matching-guidelines-and-templates.md
Labels: documentation

#2455 Add cross-ref for ISC-Veillard variant
  src/ISC-Veillard.xml
Labels: minor updates to file

#2433 Add NCBI-PD
  src/NCBI-PD.xml
  test/simpleTestForGenerator/NCBI-PD.txt
Labels: new license/exception: Accepted

#2478 Fixes rapid succession push deploy job failure bug
  .github/workflows/deploy.yaml
Labels: technical issue

#2481 Add HPND-Intel
  src/HPND-Intel.xml
  test/simpleTestForGenerator/HPND-Intel.txt
Labels: new license/exception: Accepted, used in major distro

#2476 Add 3D-Slicer-1.0
  src/3D-Slicer-1.0.xml
  test/simpleTestForGenerator/3D-Slicer-1.0.txt
Labels: new license/exception: Accepted

#2480 Apache-2.0: Break out optional end sections
  src/Apache-2.0.xml
Labels: XML markup change

#2484 New License: HPND-export2-US
  src/HPND-export2-US.xml
  test/simpleTestForGenerator/HPND-export2-US.txt
Labels: new license/exception: Accepted, used in major distro

#2486 New License: RRDtool-FLOSS-exception-2.0
  src/exceptions/RRDtool-FLOSS-exception-2.0.xml
  test/simpleTestForGenerator/RRDtool-FLOSS-exception-2.0.txt
Labels: new license/exception: Accepted, used in major distro

#2483 New License: Gutmann
  src/Gutmann.xml
  test/simpleTestForGenerator/Gutmann.txt
Labels: new license/exception: Accepted, used in major distro

#2485 New License: HPND-merchantability-variant
  src/HPND-merchantability-variant.xml
  test/simpleTestForGenerator/HPND-merchantability-variant.txt
Labels: new license/exception: Accepted, used in major distro

#2487 Fix capitalization for BSD-2-Clause-first-lines
  src/BSD-2-Clause-first-lines.xml
  test/simpleTestForGenerator/BSD-2-Clause-first-lines.txt
Labels: XML markup change, errata

#2489 Update to semver for release process docs
  DOCS/release-process.md
Labels: documentation

#2490 Add release notes for 3.24.0
  RELEASE-HISTORY.md
  RELEASE-NOTES.md
Labels: documentation
