Repository spdx/license-list-XML, pull requests merged in 2024-11, with the labels that each got.

#2593 add mxml Exception
  src/exceptions/mxml-exception.xml
  test/simpleTestForGenerator/mxml-exception.txt
Labels: new license/exception: Accepted

#2589 Update xml-fields.md
  DOCS/xml-fields.md
Labels: documentation

#2594 add Any OSI License - Perl Modules
  src/any-OSI-perl-modules.xml
  test/simpleTestForGenerator/any-OSI-perl-modules.txt
Labels: new license/exception: Accepted, used in major distro

#2601 CC-BY licenses - add optional tags where missing
  src/CC-BY-1.0.xml
  src/CC-BY-2.0.xml
  src/CC-BY-2.5.xml
  src/CC-BY-3.0-AT.xml
  src/CC-BY-3.0-AU.xml
  src/CC-BY-3.0-DE.xml
  src/CC-BY-3.0-NL.xml
  src/CC-BY-3.0-US.xml
  src/CC-BY-SA-1.0.xml
  src/CC-BY-SA-2.0-UK.xml
  src/CC-BY-SA-2.0.xml
  src/CC-BY-SA-2.5.xml
  src/CC-BY-SA-3.0-AT.xml
  src/CC-BY-SA-3.0-DE.xml
  src/CC-BY-SA-3.0.xml
Labels: XML markup change

#2574 Update Motosoto.xml
  src/Motosoto.xml
  test/simpleTestForGenerator/Motosoto.txt
Labels: OSI related

#2590 New License: CC-SA-1.0
  src/CC-SA-1.0.xml
  test/simpleTestForGenerator/CC-SA-1.0.txt
Labels: new license/exception: Accepted

#2603 New License: InnoSetup
  src/InnoSetup.xml
  test/simpleTestForGenerator/InnoSetup.txt
Labels: new license/exception: Accepted

#2602 New License: SMAIL-GPL
  src/SMAIL-GPL.xml
  test/simpleTestForGenerator/SMAIL-GPL.txt
Labels: new license/exception: Accepted, used in major distro

#2571 New License: CC-PDM-1.0
  src/CC-PDM-1.0.xml
  test/simpleTestForGenerator/CC-PDM-1.0.txt
Labels: new license/exception: Accepted

#2620 add wwl license
  src/wwl.xml
  test/simpleTestForGenerator/wwl.txt
Labels: new license/exception: Accepted, used in major distro

#2622 add CGAL-linking-exception exception
  src/exceptions/CGAL-linking-exception.xml
  test/simpleTestForGenerator/CGAL-linking-exception.txt
Labels: new license/exception: Accepted, used in major distro

#2621 add generic-xts license
  src/generic-xts.xml
  test/simpleTestForGenerator/generic-xts.txt
Labels: new license/exception: Accepted, used in major distro
