Repository spdx/license-list-XML, pull requests merged in 2024-10, with the labels that each got.

#2578 Update RELEASE-HISTORY for 3.25.0
  RELEASE-HISTORY.md
Labels: documentation

#2579 Update release process to include history
  DOCS/release-process.md
Labels: documentation

#2569 add Sendmail-Open-Source-1.1 license
  src/Sendmail-Open-Source-1.1.xml
  test/simpleTestForGenerator/Sendmail-Open-Source-1.1.txt
Labels: new license/exception: Accepted, used in major distro

#2580 Update Entessa.xml
  src/Entessa.xml
Labels: minor updates to file

#2588 change spelling of "University" in xpp license
  src/xpp.xml
Labels: XML markup change
