Repository spdx/license-list-XML, pull requests merged in 2024-02, with the labels that each got.

#2334 New Licenses: OpenSSL and SSLeay standalones
  src/OpenSSL-standalone.xml
  src/SSLeay-standalone.xml
  test/simpleTestForGenerator/OpenSSL-standalone.txt
  test/simpleTestForGenerator/SSLeay-standalone.txt
Labels: new license/exception: Accepted, used in major distro

#2245 Update link for MIT license on OSI website
  src/MIT.xml
Labels: minor updates to file

#2366 add BSD-2-Clause-Darwin license
  src/BSD-2-Clause-Darwin.xml
  test/simpleTestForGenerator/BSD-2-Clause-Darwin.txt
Labels: new license/exception: Accepted, used in major distro

#2371 add Sun-PPP license
  src/Sun-PPP.xml
  test/simpleTestForGenerator/Sun-PPP.txt
Labels: new license/exception: Accepted, used in major distro

#2372 cleanup - bulk remove empty sections
  src/BSD-4.3TAHOE.xml
  src/Furuseth.xml
  src/HPND-doc.xml
  src/Kastrup.xml
  src/SunPro.xml
  src/mailprio.xml
Labels: technical issue, XML markup change

#2363 New Exception: GNOME-examples-exception
  src/exceptions/GNOME-examples-exception.xml
  test/simpleTestForGenerator/GNOME-examples-exception.txt
Labels: new license/exception: Accepted, used in major distro

#2362 New exception: Gmsh-exception
  src/exceptions/Gmsh-exception.xml
  test/simpleTestForGenerator/Gmsh-exception.txt
Labels: new license/exception: Accepted, used in major distro

#2367 Added HPND-Fenneberg-Livingston license
  src/HPND-Fenneberg-Livingston.xml
  test/simpleTestForGenerator/HPND-Fenneberg-Livingston.txt
Labels: new license/exception: Accepted, used in major distro, HPND-variant

#2359 Updated BSD-Attribution-HPND-disclaimer to match paul-mackerras-binary
  src/BSD-Attribution-HPND-disclaimer.xml
Labels: XML markup change

#2368 add UMich-Merit license
  src/UMich-Merit.xml
  test/simpleTestForGenerator/UMich-Merit.txt
Labels: new license/exception: Accepted, used in major distro

#2373 New License: softSurfer
  src/softSurfer.xml
  test/simpleTestForGenerator/softSurfer.txt
Labels: new license/exception: Accepted, used in major distro

#2361 Add markup to GStreamer-exception-2005
  src/exceptions/GStreamer-exception-2005.xml
Labels: XML markup change

#2377 New License: CMU-Mach-nodoc
  src/CMU-Mach-nodoc.xml
  test/simpleTestForGenerator/CMU-Mach-nodoc.txt
Labels: new license/exception: Accepted, used in major distro

#2369 Autoconf-exception-generic: A variant for Gnulib
  src/exceptions/Autoconf-exception-generic.xml
Labels: XML markup change

#2364 Add markup HPND.xml
  src/HPND.xml
Labels: XML markup change

#2360 New License: Brian-Gladman-2-Clause
  src/Brian-Gladman-2-Clause.xml
  test/simpleTestForGenerator/Brian-Gladman-2-Clause.txt
Labels: new license/exception: Accepted, used in major distro

#2379 Create bcrypt-Solar-Designer.xml
  src/bcrypt-Solar-Designer.xml
  test/simpleTestForGenerator/bcrypt-Solar-Designer.txt
Labels: new license/exception: Accepted, used in major distro

#2380 Create HPND-INRIA-IMAG.xml
  src/HPND-INRIA-IMAG.xml
  test/simpleTestForGenerator/HPND-INRIA-IMAG.txt
Labels: new license/exception: Accepted, used in major distro

#2384 bzip2-1.0.6: Add optional end clause
  src/bzip2-1.0.6.xml
Labels: XML markup change

#2376 New License: OpenVision
  src/OpenVision.xml
  test/simpleTestForGenerator/OpenVision.txt
Labels: new license/exception: Accepted, used in major distro

#2381 Create gtkbook.xml
  src/gtkbook.xml
  test/simpleTestForGenerator/gtkbook.txt
Labels: new license/exception: Accepted, used in major distro

#2387 Add release notes for 3.23
  RELEASE-NOTES.md
Labels: documentation

#2392 Update README.md
  README.md
Labels: documentation

#2394 Update request-new-license.md
  DOCS/request-new-license.md
Labels: documentation

#2393 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2382 New License: MIT-Khronos-old
  src/MIT-Khronos-old.xml
  test/simpleTestForGenerator/MIT-Khronos-old.txt
Labels: new license/exception: Accepted, used in major distro

#2391 BSD-3-Clause-No-Nuclear-License: Update the license URL
  src/BSD-3-Clause-No-Nuclear-License.xml
Labels: minor updates to file

#2404 Create review.md
  DOCS/review.md
Labels: documentation

#2400 Update license-fields.md
  DOCS/license-fields.md
Labels: documentation

#2405 Update review.md
  DOCS/review.md
Labels: documentation
