Repository spdx/license-list-XML, pull requests merged in 2024-08, with the labels that each got.

#2504 Create history-OSI-SPDX (2nd try)
  DOCS/history-OSI-SPDX.md
Labels: documentation

#2527 Add new erlang-otp-linking-exception.xml
  src/exceptions/erlang-otp-linking-exception.xml
  test/simpleTestForGenerator/erlang-otp-linking-exception.txt
Labels: new license/exception: Accepted

#2539 Fix license versions for semver and typo
  RELEASE-NOTES.md
  src/3D-Slicer-1.0.xml
  src/AMD-newlib.xml
  src/BSD-2-Clause-first-lines.xml
  src/Catharon.xml
  src/Gutmann.xml
  src/HPND-Intel.xml
  src/HPND-UC-export-US.xml
  src/HPND-export-US-acknowledgement.xml
  src/HPND-export2-US.xml
  src/HPND-merchantability-variant.xml
  src/HPND-sell-variant-MIT-disclaimer-rev.xml
  src/MIT-Khronos-old.xml
  src/NCBI-PD.xml
  src/NCL.xml
  src/OAR.xml
  src/PPL.xml
  src/Sun-PPP-2000.xml
  src/X11-swapped.xml
  src/any-OSI.xml
  src/cve-tou.xml
  src/exceptions/Asterisk-linking-protocols-exception.xml
  src/exceptions/PCRE2-exception.xml
  src/exceptions/RRDtool-FLOSS-exception-2.0.xml
  src/exceptions/romic-exception.xml
  src/pkgconf.xml
  src/threeparttable.xml
  src/xzoom.xml
Labels: documentation, minor updates to file

#2538 Set W3C-20150513 to OSI-approved
  src/W3C-20150513.xml
Labels: minor updates to file

#2541 deprecate Net-SNMP.xml
  src/Net-SNMP.xml
Labels: deprecate license id

#2537 Add missing anchors B.6.4, B.15.3; Swap HTTP cases
  DOCS/license-matching-guidelines-and-templates.md
Labels: documentation

#2543 New License: DocBook-Schema
  src/DocBook-Schema.xml
  test/simpleTestForGenerator/DocBook-Schema.txt
Labels: new license/exception: Accepted, used in major distro

#2542 New License: DocBook-XML
  src/DocBook-XML.xml
  test/simpleTestForGenerator/DocBook-XML.txt
Labels: new license/exception: Accepted, used in major distro

#2545 Update license-list-XML URLs, update "The Linux Foundation"
  DOCS/license-matching-guidelines-and-templates.md
Labels: documentation

#2547 Add release notes for 3.25.0
  RELEASE-NOTES.md
Labels: documentation

#2548 Fix release process docs for incorrect HTML
  DOCS/release-process.md
Labels: documentation

#2554 add MIT-Click
  src/MIT-Click.xml
  test/simpleTestForGenerator/MIT-Click.txt
Labels: new license/exception: Accepted, used in major distro

#2555 add DocBook-Stylesheet
  src/DocBook-Stylesheet.xml
  test/simpleTestForGenerator/DocBook-Stylesheet.txt
Labels: new license/exception: Accepted, used in major distro
