Repository spdx/license-list-XML, pull requests merged in 2025-05, with the labels that each got.

#2716 markup change for cryptsetup-OpenSSL-exception
  src/exceptions/cryptsetup-OpenSSL-exception.xml
Labels: XML markup change

#2638 Correct title for cc-by-nd-2.5
  src/CC-BY-ND-2.5.xml
  test/simpleTestForGenerator/CC-BY-ND-2.5.txt
Labels: minor updates to file

#2695 Add new cross-reference to Apache-2.0.xml
  src/Apache-2.0.xml
Labels: minor updates to file, OSI related

#2741 New License: HDF5
  src/HDF5.xml
  test/simpleTestForGenerator/HDF5.txt
Labels: new license/exception: Accepted
